image: node:8.3.0

before_script:
  - sudo npm i -g bower

stages:
  - build
  - deploy

build_all:
  stage: build
  script:
    - npm install
    - npm run build


deploy_staging:
  stage: deploy
  script:
    - sh release.sh
  artifacts:
    paths:
    - conTVLauncher-linux-x64.tar.gz
  only:
  - master