image: node:8.3.0

before_script:
  - npm i -g bower

cache:
  paths:
  - conTVLauncher-linux-x64/

stages:
  - build
  - deploy

build_all:
  stage: build
  script:
    - npm install
    - npm run build
    - ls


deploy_staging:
  stage: deploy
  script:
    - ls
    - sh release.sh
  artifacts:
    paths:
    - conTVLauncher-linux-x64*.tar.gz
  only:
  - master