image: node:6.9.1

before_script:
  - npm i -g gulp bower
  - bower install --config.interactive=false --allow-root

stages:
  - build

build_all:
  stage: build
  script:
    - npm install
    - gulp
    - gulp build