image: node:6.9.1

before_script:
  - npm i -g gulp bower

stages:
  - build
  - staging

build_all:
  stage: build
  script:
    - npm install
    - gulp
    - gulp build


deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: Staging
  only:
  - master