image: node:8.3.0

before_script:
  - npm i -g bower

cache:
  paths:
  - conTVLauncher-linux-x64/

stages:
  - build
  - deploy

build_all:
  stage: build
  script:
    - npm install
    - npm run build

deploy_staging:
  stage: deploy
  script:
    - PACKAGE_VERSION="$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g')"
    - now="$(date +'%Y%m%d%H%M%S')"
    - sh release.sh
    - curl -u gitlab:$jfrogPass -T conTVLauncher-linux-x64-$now.tar.gz "http://jfrog.silvermine-productions.com/artifactory/conTVLauncher/$PACKAGE_VERSION/conTVLauncher-linux-x64-$now.tar.gz"
  artifacts:
    paths:
    - conTVLauncher-linux-x64*.tar.gz
  only:
  - master